bosfor/bosfor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', index, name="index"),
    path('products/', include('products.urls',namespace='products')),
    path('user/', include('users.urls',namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

bosfor/products/urls.py
from django.urls import path

from products.views import *

app_name = 'products'

urlpatterns = [
    path('', products, name="index"),
    path('page/<int:page>/', products, name="paginator"),
    path('<int:gender_id>/', products, name="gender"),
    path('<int:gender_id>/<int:category_id>', products, name="gendercat"),
    path('product/<int:product_id>/', product, name="product"),
    path('basket/',basket, name="basket"),
    path('basket/add/<int:product_id>',basket_add,name="basket_add"),
    path('basket/remove/<int:product_id>',basket_remove,name="basket_remove"),
    path('search/', products, name="search"),
    path('order/',order_commit, name="order")
]

bosfor/users/urls.py
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout', logout, name='logout'),
]

bosfor/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=128, default='Не указан')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.first_name + '' + self.last_name + ' | ' + self.username

bosfor/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from phonenumber_field.formfields import PhoneNumberField

from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Адрес электронной почты', widget = forms.TextInput(attrs={
        'class': 'form-control py-1', 'placeholder': 'Введите адрес эл.почты'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class':'form-control py-1', 'placeholder': 'Введите пароль'}))    

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Адрес электронной почты', widget = forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите адрес эл.почты'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class':'form-control', 'placeholder': 'Введите пароль'}))   
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={
        'class':'form-control', 'placeholder': 'Повторно введите пароль'}))   

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}))
    last_name = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите вашу фамилию'}))
    email = forms.EmailField(widget = forms.EmailInput(attrs={'class': 'form-control', 'readonly': True, 'placeholder': 'Ваш адрес эл.почты'}))
    phone = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш контактный номер телефона'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone')

bosfor/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from products.models import Basket, Order, OrderDetails
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm

# Create your views here.

def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form,
               'title': 'Вход в личный кабинет'}
    return render(request, 'users/login.html',context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
           form.save()
           messages.success(request, 'Регистрация прошла успешно!')
           return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form,
               'title': 'Регистрация пользователя'
               }
    return render(request, 'users/reg.html', context)

@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(instance = request.user, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user)

    order_details = {}
    for order in orders:
        order_details[order] = OrderDetails.objects.filter(order=order)

    context = {'title': 'Bosfor - профиль',
                'form': form,
                'baskets': Basket.objects.filter(user=request.user),
                'orders': orders,
            }
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

bosfor/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }}</title>
  <!-- Подключаем Bootstrap CSS -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}">
  {% block css %}  {% endblock css %}  
</head>
<body>
{% block content %}  {% endblock content %}

{% block footer %}  {% endblock footer %}
</body>
</html>

bosfor/users/templates/users/basket.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="static/css/basket.css">
{% endblock %}

{% block content %}
    <section class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if not baskets %}
                    <h2 class="mb-4">Ваша корзина пуста</h2>
                {% else %}
                    <h2 class="mb-4">Корзина</h2>
                    <div class="card">
                        <div class="card-body">
                            <div class="list-group">
                                <!-- Пример товара в корзине -->
                                {% for basket in baskets %}
                                <div class="list-group-item">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <img src="{{ basket.product.image_for_card.url}}" alt="Фото товара" class="img-fluid">
                                        </div>
                                        <div class="col-md-6">
                                            <h5 class="mb-1">{{basket.product.name}}</h5>
                                            <small>Размер: M</small>
                                            <div class="col-4">
                                                Кол-во: {{ basket.quantity }}шт.
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-end">
                                            <h5 class="mb-1">{{basket.sum}}руб.</h5>
                                            <a class="btn btn-sm btn-danger" href="{% url "products:basket_remove" basket.product.id%}">Удалить</a>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <hr>
                            <div class="text-end">
                                <h4>Итого: {{ baskets.all.total_sum }}руб.</h4> <!-- Исправлено здесь -->
                                <a href="{% url "products:order" %}" class="btn btn-primary">Оформить заказ</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>
  
    <script src="static/js/bootstrap.bundle.min.js"></script>
    <script src="static/js/products.js"></script>
{% endblock  %}

bosfor/users/templates/users/login.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url "users:login" %}" method="POST"> 
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p class="text-end mb-0"><a href="#">Забыли пароль?</a></p>
                            <button type="submit" class="btn btn-primary btn-block">Войти</button>
                        </form>
                    </div>
                    <div class="card-footer">
                        <p class="text-center mb-0">Нет аккаунта? <a href="{% url "users:registration" %}">Зарегистрируйтесь</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

bosfor/users/templates/users/profile.html
{% extends "products/base.html" %}
{% load static %}

{% block content %}
    <section class="container mt-5">
        <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="mb-4">Оформление профиля</h2>
            <form action="{% url "users:profile" %}" method="POST">
                {% csrf_token %}
                
            <div class="row mb-3">
                <div class="col">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                {{ form.first_name }}
                </div>
                <div class="col">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                {{ form.last_name }}
                </div>
            </div>
            <div class="mb-3">
                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label for="{{ form.phone.id_for_label }}" class="form-label">Контактный номер телефона</label>
                {{ form.phone }}
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
        </div>
        <div class="col-md-6">
            <h2 class="mb-4">История заказов</h2>
            <div class="card">
            <div class="card-body">
                <div class="list-group">
                <!-- Заказы -->
                    {% if orders %}
                        {% for order in orders %}
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">Заказ №{{ order.id }}</h5>
                                    <small>Дата: {{ order.created }}</small>
                                </div>
                                <div class="d-flex w-100 justify-content-between">
                                    <p>Сумма заказа: {{ order.sum }}</p>
                                    <small>Статус: {{ order.status }}</small>
                                </div>  
                            </a>
                        {% endfor %}
                    {% else %}
                        <h3 class="mb-4">Вы ещё не совершали покупок</h2>
                    {% endif %}
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
{% endblock content %}

bosfor/users/templates/users/reg.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Регистрация</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url "users:registration" %}" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block mb-3">Зарегистрироваться</button>
                        </form>
                    </div>
                        <div class="card-footer">
                            <p class="text-center mb-0">Уже зарегистрированы?<a href="{% url "users:login" %}">Войти</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}