bosfor/bosfor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', index, name="index"),
    path('products/', include('products.urls',namespace='products')),
    path('user/', include('users.urls',namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

bosfor/products/urls.py
from django.urls import path

from products.views import *

app_name = 'products'

urlpatterns = [
    path('', products, name="index"),
    path('page/<int:page>/', products, name="paginator"),
    path('<int:gender_id>/', products, name="gender"),
    path('<int:gender_id>/<int:category_id>', products, name="gendercat"),
    path('product/<int:product_id>/', product, name="product"),
    path('basket/',basket, name="basket"),
    path('basket/add/<int:product_id>',basket_add,name="basket_add"),
    path('basket/remove/<int:product_id>',basket_remove,name="basket_remove"),
    path('search/', products, name="search"),
    path('order/',order_commit, name="order")
]

bosfor/users/urls.py
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout', logout, name='logout'),
]

bosfor/products/models.py
from django.db import models
from users.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True, null=True, default='Описание отсутствует')
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Gender(models.Model):
    name = models.CharField(max_length=32, unique=True, null=True)

    class Meta:
        verbose_name = 'gender'
        verbose_name_plural = 'genders'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    sex = models.ForeignKey(Gender, on_delete=models.PROTECT)
    image_for_card = models.ImageField(upload_to='products_images', null=True, blank=True)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name} | Пол: {self.sex.name}'
        
class ImagesForProduct(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    image = models.ImageField(upload_to='products_images')

class QuantityOfClothes(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    XSS = models.PositiveIntegerField(default=0)
    XS = models.PositiveIntegerField(default=0)
    S = models.PositiveIntegerField(default=0)
    M = models.PositiveIntegerField(default=0)
    L = models.PositiveIntegerField(default=0)
    XL = models.PositiveIntegerField(default=0)
    XXL = models.PositiveIntegerField(default=0)
    XXL = models.PositiveIntegerField(default=0)
    ONESIZE = models.PositiveIntegerField(default=0)

class QuantityOfShoes(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    s28 = models.PositiveIntegerField(default=0)
    s29 = models.PositiveIntegerField(default=0)
    s30 = models.PositiveIntegerField(default=0)
    s31 = models.PositiveIntegerField(default=0)
    s32 = models.PositiveIntegerField(default=0)
    s33 = models.PositiveIntegerField(default=0)
    s34 = models.PositiveIntegerField(default=0)
    s35 = models.PositiveIntegerField(default=0)
    s36 = models.PositiveIntegerField(default=0)
    s37 = models.PositiveIntegerField(default=0)
    s38 = models.PositiveIntegerField(default=0)
    s39 = models.PositiveIntegerField(default=0)
    s40 = models.PositiveIntegerField(default=0)
    s41 = models.PositiveIntegerField(default=0)
    s42 = models.PositiveIntegerField(default=0)
    s43 = models.PositiveIntegerField(default=0)
    s44 = models.PositiveIntegerField(default=0)
    s45 = models.PositiveIntegerField(default=0)
    s46 = models.PositiveIntegerField(default=0)

class Reviews(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete= models.CASCADE)
    text = models.TextField()   
    eval = models.PositiveIntegerField(default=0)

class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)
    
    def total_quantity(self):
        return sum(basket.quantity for basket in self)

class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    timpestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()
    
    def __str__(self):
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

class Status(models.Model):
    name = models.CharField(32)

    def __str__(self):
        return f'{self.name}'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(Status,on_delete=models.PROTECT)
    sum = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'Заказ №{self.id} от {self.user.email}'

class OrderDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f'Товар к заказу №{self.id}'

bosfor/products/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F, Case, When
from django.db import transaction
from django.core.paginator import Paginator

from products.utils import q_search
from products.models import *



def index(request):
    context = {
        'title': 'Bosfor - главная',
        'genders': Gender.objects.all(),
        'categories': Category.objects.filter().distinct(),
        'baskets': Basket.objects.filter(user=request.user) if request.user.is_authenticated else 0,
    }
    return render(request, 'products/index.html', context)


def products(request, gender_id = None, category_id = None, page=1):
    search_query = request.GET.get('q', '')
    order_by = request.GET.get('order_by', None)

    products = Product.objects.annotate(
    total_quantity=Sum(
                Case(
                    When(
                        quantityofclothes__XS__gt=0, then=F('quantityofclothes__XS')
                    ),
                    When(
                        quantityofclothes__S__gt=0, then=F('quantityofclothes__S')
                    ),
                    When(
                        quantityofclothes__M__gt=0, then=F('quantityofclothes__M')
                    ),
                    When(
                        quantityofclothes__L__gt=0, then=F('quantityofclothes__L')
                    ),
                    When(
                        quantityofclothes__XL__gt=0, then=F('quantityofclothes__XL')
                    ),
                    When(
                        quantityofclothes__ONESIZE__gt=0, then=F('quantityofclothes__ONESIZE')
                    ),
                    default=0
                ) +
                Case(
                    When(
                        quantityofshoes__s35__gt=0, then=F('quantityofshoes__s35')
                    ),
                    When(
                        quantityofshoes__s36__gt=0, then=F('quantityofshoes__s36')
                    ),
                    When(
                        quantityofshoes__s37__gt=0, then=F('quantityofshoes__s37')
                    ),
                    When(
                        quantityofshoes__s38__gt=0, then=F('quantityofshoes__s38')
                    ),
                    When(
                        quantityofshoes__s39__gt=0, then=F('quantityofshoes__s39')
                    ),
                    When(
                        quantityofshoes__s40__gt=0, then=F('quantityofshoes__s40')
                    ),
                    When(
                        quantityofshoes__s41__gt=0, then=F('quantityofshoes__s41')
                    ),
                    When(
                        quantityofshoes__s42__gt=0, then=F('quantityofshoes__s42')
                    ),
                    When(
                        quantityofshoes__s43__gt=0, then=F('quantityofshoes__s43')
                    ),
                    When(
                        quantityofshoes__s44__gt=0, then=F('quantityofshoes__s44')
                    ),
                    When(
                        quantityofshoes__s45__gt=0, then=F('quantityofshoes__s45')
                    ),
                    When(
                        quantityofshoes__s46__gt=0, then=F('quantityofshoes__s46')
                    ),

                    default=0
                )
            )
        ).filter(total_quantity__gt=0)
    
    if gender_id:
        products = products.filter(sex_id=gender_id)  

    if category_id:
        products = products.filter(category_id=category_id)

    if search_query:
        products = q_search(search_query)

    if order_by and order_by!= "default":
        products = products.order_by(order_by)
    
    per_page = 8
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page)  

    context = {
        'title': 'Bosfor - каталог',
        'genders': Gender.objects.all(),
        'categories': Category.objects.filter().distinct(),
        'products': products_paginator,
        'baskets': Basket.objects.filter(user=request.user) if request.user.is_authenticated else 0,
    }
    return render(request, 'products/products.html', context)

def product(request, product_id=None):
    product = get_object_or_404(Product, id=product_id)

    try:
        quantity_of_clothes = QuantityOfClothes.objects.get(product=product)
    except QuantityOfClothes.DoesNotExist:
        quantity_of_clothes = None
    
    if quantity_of_clothes is None:
        quantity_of_shoes = QuantityOfShoes.objects.get(product=product)
    else:
        quantity_of_shoes = None

    context = {
        'title': product.name,
        'product': product,
        'images': ImagesForProduct.objects.filter(product=product),
        'genders': Gender.objects.all(),
        'categories': Category.objects.filter().distinct(),
        'quantity_of_clothes': quantity_of_clothes,
        'quantity_of_shoes': quantity_of_shoes,
        'baskets': Basket.objects.filter(user=request.user) if request.user.is_authenticated else 0,
    }
    return render(request, 'products/product.html',context)

@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    
    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity = 1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def basket_remove(request, product_id):
    try:
        basket_item = Basket.objects.get(user=request.user, product=product_id)
        basket_item.delete()
    except Basket.DoesNotExist:
        pass
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def basket(request):
    context = {'title': 'Bosfor - корзина',
            'baskets': Basket.objects.filter(user=request.user), 
        }
    return render(request, 'users/basket.html', context)

@login_required
def order_commit(request):
    baskets = Basket.objects.filter(user=request.user)
 
    with transaction.atomic():
        order = Order.objects.create(user=request.user, status=Status.objects.get(name='В обработке'))
        
        total_sum = 0
        for basket in baskets:
            OrderDetails.objects.create(order=order, product=basket.product, quantity=basket.quantity)
            total_sum += basket.sum()
        order.sum = total_sum
        order.save()
        baskets.delete()
    
    return redirect('users:profile')

bosfor/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bosfor - главная</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!--Кастомный стиль для шаблона-->
    {% block css %} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url "index" %}"><img src="{% static "img/logo.png" %}" alt="" class="logo"></a>
            <div class="order-lg-last">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url "products:basket" %}" class="nav-link position-relative"><img src="{% static "img/basket.svg" %}" alt="" class="icons"> <span class="position-absolute top-10 start-0 translate-middle badge rounded-pill bg-danger">
                        {{ baskets.total_quantity }}</a></li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><img src="{% static "img/user.svg" %}" alt="" class="icons"></a>
                        <ul class="dropdown-menu">
                            
                            <li class="dropdown-item"><a href="{% url "users:profile" %}">Профиль</a></li>
                            {% if user.is_superuser or user.is_staff %}
                                <li class="dropdown-item"><a href="{% url 'admin:index' %}">Админ-панель</a></li>
                                <li class="dropdown-item"><a href="#">Аналитика</a></li>
                            {% endif %}
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><a href="{% url "users:logout" %}">Выйти</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url "users:login" %}" class="nav-link">
                            <img src="{% static "img/login.svg" %}" alt="" class="icons">
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navcat" aria-controls="navcat" aria-expanded="false" aria-label="Меню">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navcat">
                <ul class="navbar-nav mr-auto">
                    {% for gender in genders %}
                        <li class="nav-item dropdown ctgs">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><b>{{ gender.name }}</b></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-item"><a href="{% url "products:gender" gender.id %}">Все товары</a></li>
                                <li class="dropdown-header">По категориям:</li>
                                {% for category in categories %}
                                    <li class="dropdown-item"><a href="{% url "products:gendercat" gender.id category.id%}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                    <li class="nav-item ctgs"><a href="#" class="nav-link" >О нас</a></li>
                </ul>
            </div>
        </div>
    </nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

bosfor/products/templates/products/index.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href=" {% static "css/index.css" %}">
{% endblock %}

{% block content %}
    <section>
        <div class="container text-center">
            <div class="row">
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
                <div class="col mt-5">
                    <a href="{% url "products:index" %}" class="hdr btn">Перейти к ассортименту</a>
                </div>
            </div>
        </div>
          
    </section>
{% endblock %}

bosfor/products/templates/products/product.html
{% extends "products/base.html" %}
{% load static %}


{% block content %}
<!-- Контент страницы -->
<section class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div id="carouselIndicators" class="carousel slide">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ product.image_for_card.url }}" class="d-block w-100" alt="...">
                    </div>
                    {%for img in images%}
                        <div class="carousel-item">
                            <img src="{{ img.image.url }}" class="d-block w-100" alt="...">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden"></span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden"></span>
                </button>
              </div>
        </div>
        <div class="col-md-6">
        <h2>{{ product.name }}</h2>
        <p>{{ product.description }}</p>
        <div class="col-6 mb-2 mt-5">
            <h4>Цена: {{ product.price }}₽</h4>
            <label for="sizeSelect" class="form-label">Выберите размер:</label>
            <select class="form-select" id="sizeSelect">
                <option selected disabled>Выберите размер</option>
                {% if quantity_of_clothes.XS or quantity_of_clothes.S or quantity_of_clothes.M or quantity_of_clothes.L or quantity_of_clothes.XL %}
                    {% if quantity_of_clothes.XS%}
                        <option value="XS">
                            XS - на складе {{ quantity_of_clothes.XS }}шт.
                        </option>
                    {% else %}
                        <option disabled>XS - товар закончился</option>
                    {% endif %}
                    {% if quantity_of_clothes.S%}
                        <option value="S">
                            S - на складе {{ quantity_of_clothes.S }}шт.
                        </option>
                    {% else %}
                        <option disabled>S - товар закончился</option>
                    {% endif %}
                    {% if quantity_of_clothes.M %}
                        <option value="M">
                            M - на складе {{ quantity_of_clothes.M }}шт.
                        </option>
                    {% else %}
                        <option disabled>M - товар закончился</option>
                    {% endif %}
                    {% if quantity_of_clothes.L %}
                        <option value="L">
                            L - на складе {{ quantity_of_clothes.L }}шт.
                        </option>
                    {% else %}
                        <option disabled>L - товар закончился</option>
                    {% endif %}
                    {% if quantity_of_clothes.XL %}
                        <option value="XL">
                            XL - на складе {{ quantity_of_clothes.XL }}шт.
                        </option>
                    {% else %}
                        <option disabled>XL - товар закончился</option>
                    {% endif %}
                {%elif quantity_of_clothes.ONESIZE %}
                    <option value="onesize">
                        ONESIZE - на складе {{ quantity_of_clothes.ONESIZE }}шт.
                    </option>
                {% else %}

                    {% if quantity_of_shoes.s35%}
                        <option value="35">
                            35RU - на складе {{ quantity_of_shoes.s35 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s36%}
                        <option value="36">
                            35RU - на складе {{ quantity_of_shoes.s36 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s37%}
                        <option value="37">
                            37RU - на складе {{ quantity_of_shoes.s37 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s38 %}
                        <option value="38">
                            38RU - на складе {{ quantity_of_shoes.s38 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s39 %}
                        <option value="39">
                            39RU - на складе {{ quantity_of_shoes.s39 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s40 %}
                        <option value="40">
                            40RU - на складе {{ quantity_of_shoes.s40 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s41 %}
                        <option value="41">
                            41RU - на складе {{ quantity_of_shoes.s41 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s42 %}
                        <option value="42">
                            42RU - на складе {{ quantity_of_shoes.s42 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s43 %}
                        <option value="43">
                            43RU - на складе {{ quantity_of_shoes.s43 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s44 %}
                        <option value="44">
                            44RU - на складе {{ quantity_of_shoes.s44 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s45 %}
                        <option value="45">
                            45RU - на складе {{ quantity_of_shoes.s45 }}шт.
                        </option>
                    {% endif %}

                    {% if quantity_of_shoes.s46 %}
                        <option v
                    {% endif %}

                {% endif %}
            </select>
        </div>
            <a class="btn btn-primary" href="{% url "products:basket_add" product.id %}">Добавить в корзину</a> 
        </div>
        </div>
        </section>
{% endblock content %}

bosfor/products/templates/products/products.html
{% extends "products/base.html" %}
{% load static %}

{% block content %}
<!-- Контент страницы -->
<section>
    <div class="container mt-5">
        {% if not products %}
            <h1> Товары в данной категории закончились, либо их нет. </h1>  
        {% else %}
            <h1>Наш ассортимент</h1>
            <div class="row mt-5">
                <div class="col-4">
                <!-- Поиск по названию -->
                    <form class="d-flex" action="{% url 'products:search' %}" method="GET">
                        <input type="text" class="form-control me-2" name="q" placeholder="Поиск по названию">
                        <button class="btn btn-primary" type="submit">Поиск</button>
                    </form>
                </div>
                <div class="col-5">

                </div>
                <div class="col-3">
                    <!-- Меню сортировки -->
                    <form class="row" action="{% if request.GET.q %} {% url "products:search" %}{% else %}{% url "products:index" %}{% endif %}" method="get">
                        <div class="col">
                            <select class="form-control" id="sort" name="order_by">
                                <option selected disabled>Сортировка</option>
                                <option value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %} selected {% endif %}>По умолчанию</option>
                                <option value="price" {% if request.GET.order_by == 'price' %} selected {% endif %}>Цена по возрастанию</option>
                                <option value="-price" {% if request.GET.order_by == '-price' %} selected {% endif %}>Цена по убыванию</option>
                            </select>
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-primary" type="submit">Ok</button>
                        </div>
                    </form>
                </div>               
             </div>
            <div class="row mt-5">
            <!--  Карточки товаров -->
                {% for product in products %}
                    <div class="col-md-3 mb-3">
                    <div class="card">
                        <a href="{% url "products:product" product.id %}">
                            {% if product.image_for_card.url %}
                                <img class="card-img-top" src="{{ product.image_for_card.url }}" alt="Товар">
                            {% else %}
                                <img class="card-img-top" src="https://via.placeholder.com/300" alt="Товар">
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <a href="{% url "products:product" product.id %}" class="frst"><h5 class="card-title">{{ product.name }}</h5></a>
                            <div class="row">
                                <div class="col-8">
                                    {{ product.price }} руб.
                                </div>
                                <div class="col-4">
                                    <a href="{% url "products:product" product.id %}" class="btn btn-primary">Купить</a>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Пагинация -->
            <ul class="pagination justify-content-center mt-4">
                <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                <a class="page-link" 
                href="{% if products.has_previous %} {% url "products:paginator" products.previous_page_number %} {% else %} # {% endif %}" 
                aria-disabled="true" tabindex="-1">
                    Предыдущий
                    </a>
                </li>
                {% for page_num in products.paginator.page_range %}
                    <li class="page-item {% if page_num == products.number %}active{% endif %}" aria-current="page">
                        <a class="page-link" href="{% url 'products:paginator' page_num %}">
                            {{ page_num }}
                        </a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if products.has_next %} {% url "products:paginator" products.next_page_number %} {% else %} # {% endif %}">Следующий</a>
                </li>
            </ul>
        </div>
    {% endif %}
</section>
{% endblock content %}